version: '3'

vars:
  CORE_DIR: core/
  UI_DIR: ui/
  IMAGE_BASE: redstash
  # Directory for Go source commands
  GO_CMD_DIR: cmd
  # Directory for build output
  BUILD_DIR: build

tasks:
  default:
    desc: "Lists all available tasks"
    cmds:
      - task --list --sort=alphanumeric

  keystore:
    cmds:
      - keytool -genkeypair
        -v
        -keystore key.jks
        -alias my-key-alias
        -keyalg RSA
        -keysize 2048
        -validity 10000
      - coreutils base64 key.jks > key.jks.base64
