name: redstash
description: "Client for redstash server"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  media_kit: ^1.2.1 # Primary package.
  media_kit_video: ^1.3.1 # For video rendering.
  media_kit_libs_video: ^1.0.7 # Native video dependencies.
  permission_handler: ^12.0.1

  # state management
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.3

  # networking
  web: ^1.1.1
  http: ^1.5.0
  connectrpc:
  grpc: ^4.1.0
  protobuf: ^4.2.0


  # ui
  flutter_animate: ^4.5.2
  timeago: ^3.7.1
  font_awesome_flutter: ^10.12.0
  cached_network_image: ^3.4.1
  intl:

  # misc
  shared_preferences: ^2.5.3
  url_launcher:
  fixnum: ^1.1.1
  logger: ^2.6.2
  flutter_html: ^3.0.0

dev_dependencies:
  custom_lint: ^0.7.6
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  image_path: "assets/gouda.png"

  android: "launcher_icon"
  min_sdk_android: 21

  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/gouda.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/gouda.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/gouda.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package