name: Dev Docker Build

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ui/**
      - core/**
      - Dockerfile
      - ./.github/workflows/action-docker.yml
      - ./.github/workflows/action-docker-combine.yml

permissions:
  contents: write
  packages: write

env:
  TITLE: redstash
  DOCKERFILE: Dockerfile
  VERSION_TAG: v1.0.0
  source_branch: main

jobs:
  build-amd64:
    uses: ./.github/workflows/action-docker.yml
    with:
      title: ${{ env.TITLE }}
      dockerfile: ${{ env.DOCKERFILE }}
      version_tag: ${{ env.VERSION_TAG }}
      source_branch: ${{ env.SOURCE_BRANCH }}
      platform: linux/amd64
      arch_suffix: amd64
      machine: ubuntu-latest

  build-arm64:
    uses: ./.github/workflows/action-docker.yml
    with:
      title: ${{ env.TITLE }}
      dockerfile: ${{ env.DOCKERFILE }}
      version_tag: ${{ env.VERSION_TAG }}
      source_branch: ${{ env.SOURCE_BRANCH }}
      platform: linux/arm64
      arch_suffix: arm64
      machine: ubuntu-24.04-arm

  combine:
    uses: ./.github/workflows/action-docker-combine.yml
    needs: [ build-amd64, build-arm64 ]
    with:
      title: ${{ env.TITLE }}
      version_tag: ${{ env.VERSION_TAG }}
      is_latest: true
      build_amd64: true
      build_arm64: true
