name: Dev Docker Build

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ui/**
      - core/**
      - Dockerfile
      - .github/workflows/action-docker.yml

permissions:
  contents: write
  packages: write

jobs:
  build-docker:
    name: docker
    uses: ./.github/workflows/action-docker.yml
    with:
      source_branch: ${{ github.ref_name }}
      version_tag: 'dev'
    secrets: inherit
